[package]
name = "xformed-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
clap = { version = "4", features = ["derive"] }
base64 = "0.22"
serde_json = "1"

# local crate
converters = { path = "../converters" }
